### ISSUE TITLE
Resource pack won't create

### ISSUE THREAD

**Issue by SanjivanM** [keotl/mcdisc-resource-builder#10] opened 2020-01-16 04:21 UTC
I could be doing this wrong, so if I am, sorry in advance.  Let me describe what I've tried:

1. Run the .exe
2. Select the disc list with the video
3. Press "build resource pack"

It says that the video was unavailable, so I tried a file path.  Nothing works.  I've attached the JSON (as a .txt) that I'm trying to use.

The JSON has the Youtube URL
[SM_DiscList.txt](https://github.com/keotl/mcdisc-resource-builder/files/4069307/SM_DiscList.txt)

**Comment by keotl** [comment] 2020-01-16 23:43
Hi, there is nothing wrong with your setup. The issue is caused by the youtube library this project uses having not been updated in a few months. 

If have pushed a fix to this repo, but I have not yet had the time to nicely package the .exe. So if you are confident with running this project from source, you should be able to build your resource pack that way. In any case, I will try to provide the newly updated executables in the coming week. I will update this issue once this is done.

Cheers,

**Comment by SanjivanM** [comment] 2020-01-17 00:23
Ok, I'll wait for the exe... Python from source isn't my thing :P

**Comment by SanjivanM** [comment] 2020-01-22 02:58
So I tried to create an exe, but Windows said that "pyinstaller" wasn't recognized.  I do have all necessary stuff installed as indicated in the readme, though

**Comment by keotl** [comment] 2020-01-22 21:37
It would appear that the pyinstaller script does not get added properly to Windows' path variable, which is always a pain to get to work correctly compared to linux. 
Anyway, I published a new windows executable available on the readme. This link should get automatically updated whenever I push code updates to this repo. [https://ci.appveyor.com/project/keotl/mcdisc-resource-builder/build/artifacts](https://ci.appveyor.com/project/keotl/mcdisc-resource-builder/build/artifacts)

Let me know if you have any more issues.

**Closed by keotl** 2020-01-22 21:37 UTC
